language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
#   - hhvm

# https://docs.travis-ci.com/user/reference/trusty#PHP-images
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3.3
      dist: precise
# matrix:
#   allow_failures:
#     - php: hhvm

before_script:
  - chmod 777 -R ./
  - php -m
  - cd build

script:
  - php build -n holy_lance
  - php -l holy_lance.php
  # - php -S 0.0.0.0:8080 &
  # - curl -s http://localhost:8080/holy_lance.php?file=init.php
  # - curl -s http://localhost:8080/holy_lance.php?file=api.php
  - php-cgi -f holy_lance.php file=init.php
  - php-cgi -f holy_lance.php file=api.php
  - php-cgi -f holy_lance.php file=test_disk.php
  - php-cgi -f holy_lance.php