language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - chmod 777 -R ./
  - php -m
  - cd build

script:
  - php build
  - php -l probe.php
  # - php -S 0.0.0.0:8080 &
  # - curl -s http://localhost:8080/probe.php?file=init.php
  # - curl -s http://localhost:8080/probe.php?file=api.php
  - php-cgi -f probe.php file=init.php
  - php-cgi -f probe.php file=api.php