language: php
php:
  - '5.2'
  - '5.3.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
#   - hhvm

# matrix:
#   allow_failures:
#     - php: hhvm

before_script:
  - chmod 777 -R ./
  - php -m
  - cd build

script:
  - php build
  - php -l holy_lance.php
  # - php -S 0.0.0.0:8080 &
  # - curl -s http://localhost:8080/holy_lance.php?file=init.php
  # - curl -s http://localhost:8080/holy_lance.php?file=api.php
  - php-cgi -f holy_lance.php file=init.php
  - php-cgi -f holy_lance.php file=api.php
  - php-cgi -f holy_lance.php